import 'package:flutter/material.dart';
import 'package:roadies/main.dart';
import 'package:roadies/pages/home_page.dart';
import 'package:roadies/requests/squad_service.dart';

class CreateSquadPage extends StatefulWidget {
  const CreateSquadPage({super.key});

  @override
  CreateSquadPageState createState() => CreateSquadPageState();
}

class CreateSquadPageState extends State<CreateSquadPage> {
  final _formKey = GlobalKey<FormState>();
  String _squadName = '';
  String _squadDescription = '';
  int _squadCapacity = 0;
  int _squadRange = 0;

  Future<void> _createSquad() async {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();
      final squadData = {
        'squadName': _squadName,
        'squadDescription': _squadDescription,
        'squadCapacity': _squadCapacity,
        'squadRange': _squadRange,
        'userId': await getUserId(),
      };

      // Convert squadData to Squad object
      // final squad = Squad(
      //   id: 0, // Assuming ID is generated by the server
      //   squadName: _squadName,
      //   squadDescription: _squadDescription,
      //   squadCapacity: _squadCapacity,
      //   squadRange: _squadRange,
      //   createdAt: DateTime.now(),
      //   updatedAt: DateTime.now(),
      //   isExpired: false,
      // );

      await SquadService.createSquad(
          squadData); // Assuming SquadService.createSquad accepts JSON

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Squad created successfully')),
        );
        Navigator.of(context).pushReplacement(
            MaterialPageRoute(builder: (context) => const HomePage()));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Squad'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: <Widget>[
              TextFormField(
                decoration: const InputDecoration(labelText: 'Squad Name'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter squad name';
                  }
                  return null;
                },
                onSaved: (value) {
                  _squadName = value!;
                },
              ),
              TextFormField(
                decoration:
                    const InputDecoration(labelText: 'Squad Description'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter squad description';
                  }
                  return null;
                },
                onSaved: (value) {
                  _squadDescription = value!;
                },
              ),
              TextFormField(
                decoration: const InputDecoration(labelText: 'Squad Capacity'),
                validator: (value) {
                  if (value == null ||
                      value.isEmpty ||
                      int.tryParse(value) == null) {
                    return 'Please enter a valid number';
                  }
                  return null;
                },
                onSaved: (value) {
                  _squadCapacity = int.parse(value!);
                },
              ),
              TextFormField(
                decoration: const InputDecoration(labelText: 'Squad Range'),
                validator: (value) {
                  if (value == null ||
                      value.isEmpty ||
                      int.tryParse(value) == null) {
                    return 'Please enter a valid number';
                  }
                  return null;
                },
                onSaved: (value) {
                  _squadRange = int.parse(value!);
                },
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: _createSquad,
                child: const Text('Create'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
